# source: https://stockanalysis.com/stocks/screener/

# Healthcare: Drug Manufacturers - Specialty & Generic, Biotechnology, Medical Devices
# Energy: Oil & Gas Exploration & Production, Oil & Gas Integrated, Oil & Gas Midstream
# Technology: Software - Application, Software - Infrastructure, Semiconductors

# sector, industry_name, symbol, company_name
ALL_STOCKS = [
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'ZTS', 'Zoetis Inc.'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'HLN', 'Haleon plc'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'TAK', 'Takeda Pharmaceutical Company Limited'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'TEVA', 'Teva Pharmaceutical Industries Limited'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'VTRS', 'Viatris Inc.'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'NBIX', 'Neurocrine Biosciences, Inc.'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'RDY', "Dr. Reddy's Laboratories Limited"),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'CTLT', 'Catalent, Inc.'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'ITCI', 'Intra-Cellular Therapies, Inc.'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'LNTH', 'Lantheus Holdings, Inc.'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'ELAN', 'Elanco Animal Health Incorporated'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'ALKS', 'Alkermes plc'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'PBH', 'Prestige Consumer Healthcare Inc.'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'PRGO', 'Perrigo Company plc'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'ALVO', 'Alvotech'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'BHC', 'Bausch Health Companies Inc.'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'HCM', 'HUTCHMED (China) Limited'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'AMRX', 'Amneal Pharmaceuticals, Inc.'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'AMPH', 'Amphastar Pharmaceuticals, Inc.'),
    ('Healthcare', 'Drug Manufacturers - Specialty & Generic', 'SUPN', 'Supernus Pharmaceuticals, Inc.'),
    ('Healthcare', 'Biotechnology', 'VRTX', 'Vertex Pharmaceuticals Incorporated'),
    ('Healthcare', 'Biotechnology', 'REGN', 'Regeneron Pharmaceuticals, Inc.'),
    ('Healthcare', 'Biotechnology', 'ARGX', 'argenx SE'),
    ('Healthcare', 'Biotechnology', 'ALNY', 'Alnylam Pharmaceuticals, Inc.'),
    ('Healthcare', 'Biotechnology', 'BNTX', 'BioNTech SE'),
    ('Healthcare', 'Biotechnology', 'BGNE', 'BeiGene, Ltd.'),
    ('Healthcare', 'Biotechnology', 'UTHR', 'United Therapeutics Corporation'),
    ('Healthcare', 'Biotechnology', 'MRNA', 'Moderna, Inc.'),
    ('Healthcare', 'Biotechnology', 'INCY', 'Incyte Corporation'),
    ('Healthcare', 'Biotechnology', 'GMAB', 'Genmab A/S'),
    ('Healthcare', 'Biotechnology', 'INSM', 'Insmed Incorporated'),
    ('Healthcare', 'Biotechnology', 'BMRN', 'BioMarin Pharmaceutical Inc.'),
    ('Healthcare', 'Biotechnology', 'TECH', 'Bio-Techne Corporation'),
    ('Healthcare', 'Biotechnology', 'SRPT', 'Sarepta Therapeutics, Inc.'),
    ('Healthcare', 'Biotechnology', 'PCVX', 'Vaxcyte, Inc.'),
    ('Healthcare', 'Biotechnology', 'EXEL', 'Exelixis, Inc.'),
    ('Healthcare', 'Biotechnology', 'ASND', 'Ascendis Pharma A/S'),
    ('Healthcare', 'Biotechnology', 'JAZZ', 'Jazz Pharmaceuticals plc'),
    ('Healthcare', 'Biotechnology', 'MDGL', 'Madrigal Pharmaceuticals, Inc.'),
    ('Healthcare', 'Biotechnology', 'LEGN', 'Legend Biotech Corporation'),
    ('Healthcare', 'Medical Devices', 'ABT', 'Abbott Laboratories'),
    ('Healthcare', 'Medical Devices', 'SYK', 'Stryker Corporation'),
    ('Healthcare', 'Medical Devices', 'BSX', 'Boston Scientific Corporation'),
    ('Healthcare', 'Medical Devices', 'MDT', 'Medtronic plc'),
    ('Healthcare', 'Medical Devices', 'EW', 'Edwards Lifesciences Corporation'),
    ('Healthcare', 'Medical Devices', 'DXCM', 'DexCom, Inc.'),
    ('Healthcare', 'Medical Devices', 'PHG', 'Koninklijke Philips N.V.'),
    ('Healthcare', 'Medical Devices', 'ZBH', 'Zimmer Biomet Holdings, Inc.'),
    ('Healthcare', 'Medical Devices', 'STE', 'STERIS plc'),
    ('Healthcare', 'Medical Devices', 'PODD', 'Insulet Corporation'),
    ('Healthcare', 'Medical Devices', 'GMED', 'Globus Medical, Inc.'),
    ('Healthcare', 'Medical Devices', 'SNN', 'Smith & Nephew plc'),
    ('Healthcare', 'Medical Devices', 'MASI', 'Masimo Corporation'),
    ('Healthcare', 'Medical Devices', 'PEN', 'Penumbra, Inc.'),
    ('Healthcare', 'Medical Devices', 'BIO', 'Bio-Rad Laboratories, Inc.'),
    ('Healthcare', 'Medical Devices', 'BRKR', 'Bruker Corporation'),
    ('Healthcare', 'Medical Devices', 'GKOS', 'Glaukos Corporation'),
    ('Healthcare', 'Medical Devices', 'INSP', 'Inspire Medical Systems, Inc.'),
    ('Healthcare', 'Medical Devices', 'ITGR', 'Integer Holdings Corporation'),
    ('Energy', 'Oil & Gas Exploration & Production', 'COP', 'ConocoPhillips'),
    ('Energy', 'Oil & Gas Exploration & Production', 'EOG', 'EOG Resources, Inc.'),
    ('Energy', 'Oil & Gas Exploration & Production', 'CNQ', 'Canadian Natural Resources Limited'),
    ('Energy', 'Oil & Gas Exploration & Production', 'FANG', 'Diamondback Energy, Inc.'),
    ('Energy', 'Oil & Gas Exploration & Production', 'OXY', 'Occidental Petroleum Corporation'),
    ('Energy', 'Oil & Gas Exploration & Production', 'HES', 'Hess Corporation'),
    ('Energy', 'Oil & Gas Exploration & Production', 'WDS', 'Woodside Energy Group Ltd'),
    ('Energy', 'Oil & Gas Exploration & Production', 'TPL', 'Texas Pacific Land Corporation'),
    ('Energy', 'Oil & Gas Exploration & Production', 'EQT', 'EQT Corporation'),
    ('Energy', 'Oil & Gas Exploration & Production', 'EXE', 'Expand Energy Corporation'),
    ('Energy', 'Oil & Gas Exploration & Production', 'DVN', 'Devon Energy Corporation'),
    ('Energy', 'Oil & Gas Exploration & Production', 'CTRA', 'Coterra Energy Inc.'),
    ('Energy', 'Oil & Gas Exploration & Production', 'PR', 'Permian Resources Corporation'),
    ('Energy', 'Oil & Gas Exploration & Production', 'OVV', 'Ovintiv Inc.'),
    ('Energy', 'Oil & Gas Exploration & Production', 'AR', 'Antero Resources Corporation'),
    ('Energy', 'Oil & Gas Exploration & Production', 'RRC', 'Range Resources Corporation'),
    ('Energy', 'Oil & Gas Exploration & Production', 'APA', 'APA Corporation'),
    ('Energy', 'Oil & Gas Exploration & Production', 'CHRD', 'Chord Energy Corporation'),
    ('Energy', 'Oil & Gas Exploration & Production', 'MTDR', 'Matador Resources Company'),
    ('Energy', 'Oil & Gas Exploration & Production', 'CNX', 'CNX Resources Corporation'),
    ('Energy', 'Oil & Gas Integrated', 'XOM', 'Exxon Mobil Corporation'),
    ('Energy', 'Oil & Gas Integrated', 'CVX', 'Chevron Corporation'),
    ('Energy', 'Oil & Gas Integrated', 'SHEL', 'Shell plc'),
    ('Energy', 'Oil & Gas Integrated', 'TTE', 'TotalEnergies SE'),
    ('Energy', 'Oil & Gas Integrated', 'PBR.A', 'Petróleo Brasileiro S.A. - Petrobras'),
    ('Energy', 'Oil & Gas Integrated', 'PBR', 'Petróleo Brasileiro S.A. - Petrobras'),
    ('Energy', 'Oil & Gas Integrated', 'BP', 'BP p.l.c.'),
    ('Energy', 'Oil & Gas Integrated', 'EQNR', 'Equinor ASA'),
    ('Energy', 'Oil & Gas Integrated', 'SU', 'Suncor Energy Inc.'),
    ('Energy', 'Oil & Gas Integrated', 'E', 'Eni S.p.A.'),
    ('Energy', 'Oil & Gas Integrated', 'IMO', 'Imperial Oil Limited'),
    ('Energy', 'Oil & Gas Integrated', 'CVE', 'Cenovus Energy Inc.'),
    ('Energy', 'Oil & Gas Integrated', 'YPF', 'YPF Sociedad Anónima'),
    ('Energy', 'Oil & Gas Integrated', 'EC', 'Ecopetrol S.A.'),
    ('Energy', 'Oil & Gas Integrated', 'NFG', 'National Fuel Gas Company'),
    ('Energy', 'Oil & Gas Integrated', 'TGS', 'Transportadora de Gas del Sur S.A.'),
    ('Energy', 'Oil & Gas Integrated', 'SLNG', 'Stabilis Solutions, Inc.'),
    ('Energy', 'Oil & Gas Midstream', 'ENB', 'Enbridge Inc.'),
    ('Energy', 'Oil & Gas Midstream', 'EPD', 'Enterprise Products Partners L.P.'),
    ('Energy', 'Oil & Gas Midstream', 'WMB', 'The Williams Companies, Inc.'),
    ('Energy', 'Oil & Gas Midstream', 'ET', 'Energy Transfer LP'),
    ('Energy', 'Oil & Gas Midstream', 'OKE', 'ONEOK, Inc.'),
    ('Energy', 'Oil & Gas Midstream', 'KMI', 'Kinder Morgan, Inc.'),
    ('Energy', 'Oil & Gas Midstream', 'MPLX', 'MPLX LP'),
    ('Energy', 'Oil & Gas Midstream', 'TRP', 'TC Energy Corporation'),
    ('Energy', 'Oil & Gas Midstream', 'LNG', 'Cheniere Energy, Inc.'),
    ('Energy', 'Oil & Gas Midstream', 'TRGP', 'Targa Resources Corp.'),
    ('Energy', 'Oil & Gas Midstream', 'CQP', 'Cheniere Energy Partners, L.P.'),
    ('Energy', 'Oil & Gas Midstream', 'PBA', 'Pembina Pipeline Corporation'),
    ('Energy', 'Oil & Gas Midstream', 'WES', 'Western Midstream Partners, LP'),
    ('Energy', 'Oil & Gas Midstream', 'PAA', 'Plains All American Pipeline, L.P.'),
    ('Energy', 'Oil & Gas Midstream', 'DTM', 'DT Midstream, Inc.'),
    ('Energy', 'Oil & Gas Midstream', 'VNOM', 'Viper Energy, Inc.'),
    ('Energy', 'Oil & Gas Midstream', 'KNTK', 'Kinetik Holdings Inc.'),
    ('Energy', 'Oil & Gas Midstream', 'HESM', 'Hess Midstream LP'),
    ('Energy', 'Oil & Gas Midstream', 'AM', 'Antero Midstream Corporation'),
    ('Energy', 'Oil & Gas Midstream', 'ENLC', 'EnLink Midstream, LLC'),
    ('Technology', 'Software - Application', 'CRM', 'Salesforce, Inc.'),
    ('Technology', 'Software - Application', 'SAP', 'SAP SE'),
    ('Technology', 'Software - Application', 'NOW', 'ServiceNow, Inc.'),
    ('Technology', 'Software - Application', 'INTU', 'Intuit Inc.'),
    ('Technology', 'Software - Application', 'SHOP', 'Shopify Inc.'),
    ('Technology', 'Software - Application', 'UBER', 'Uber Technologies, Inc.'),
    ('Technology', 'Software - Application', 'ADP', 'Automatic Data Processing, Inc.'),
    ('Technology', 'Software - Application', 'MSTR', 'MicroStrategy Incorporated'),
    ('Technology', 'Software - Application', 'CDNS', 'Cadence Design Systems, Inc.'),
    ('Technology', 'Software - Application', 'WDAY', 'Workday, Inc.'),
    ('Technology', 'Software - Application', 'TEAM', 'Atlassian Corporation'),
    ('Technology', 'Software - Application', 'TTD', 'The Trade Desk, Inc.'),
    ('Technology', 'Software - Application', 'ADSK', 'Autodesk, Inc.'),
    ('Technology', 'Software - Application', 'ROP', 'Roper Technologies, Inc.'),
    ('Technology', 'Software - Application', 'FICO', 'Fair Isaac Corporation'),
    ('Technology', 'Software - Application', 'DDOG', 'Datadog, Inc.'),
    ('Technology', 'Software - Application', 'PAYX', 'Paychex, Inc.'),
    ('Technology', 'Software - Application', 'HUBS', 'HubSpot, Inc.'),
    ('Technology', 'Software - Application', 'ANSS', 'ANSYS, Inc.'),
    ('Technology', 'Software - Application', 'TYL', 'Tyler Technologies, Inc.'),
    ('Technology', 'Software - Infrastructure', 'MSFT', 'Microsoft Corporation'),
    ('Technology', 'Software - Infrastructure', 'ORCL', 'Oracle Corporation'),
    ('Technology', 'Software - Infrastructure', 'ADBE', 'Adobe Inc.'),
    ('Technology', 'Software - Infrastructure', 'PANW', 'Palo Alto Networks, Inc.'),
    ('Technology', 'Software - Infrastructure', 'CRWD', 'CrowdStrike Holdings, Inc.'),
    ('Technology', 'Software - Infrastructure', 'SNPS', 'Synopsys, Inc.'),
    ('Technology', 'Software - Infrastructure', 'FTNT', 'Fortinet, Inc.'),
    ('Technology', 'Software - Infrastructure', 'SQ', 'Block, Inc.'),
    ('Technology', 'Software - Infrastructure', 'NET', 'Cloudflare, Inc.'),
    ('Technology', 'Software - Infrastructure', 'ZS', 'Zscaler, Inc.'),
    ('Technology', 'Software - Infrastructure', 'GDDY', 'GoDaddy Inc.'),
    ('Technology', 'Software - Infrastructure', 'CPAY', 'Corpay, Inc.'),
    ('Technology', 'Software - Infrastructure', 'CHKP', 'Check Point Software Technologies Ltd.'),
    ('Technology', 'Software - Infrastructure', 'MDB', 'MongoDB, Inc.'),
    ('Technology', 'Software - Infrastructure', 'VRSN', 'VeriSign, Inc.'),
    ('Technology', 'Software - Infrastructure', 'GEN', 'Gen Digital Inc.'),
    ('Technology', 'Software - Infrastructure', 'NTNX', 'Nutanix, Inc.'),
    ('Technology', 'Software - Infrastructure', 'TWLO', 'Twilio Inc.'),
    ('Technology', 'Software - Infrastructure', 'FFIV', 'F5, Inc.'),
    ('Technology', 'Software - Infrastructure', 'AKAM', 'Akamai Technologies, Inc.'),
    ('Technology', 'Semiconductors', 'NVDA', 'NVIDIA Corporation'),
    ('Technology', 'Semiconductors', 'AVGO', 'Broadcom Inc.'),
    ('Technology', 'Semiconductors', 'TSM', 'Taiwan Semiconductor Manufacturing Company Limited'),
    ('Technology', 'Semiconductors', 'AMD', 'Advanced Micro Devices, Inc.'),
    ('Technology', 'Semiconductors', 'QCOM', 'QUALCOMM Incorporated'),
    ('Technology', 'Semiconductors', 'TXN', 'Texas Instruments Incorporated'),
    ('Technology', 'Semiconductors', 'MU', 'Micron Technology, Inc.'),
    ('Technology', 'Semiconductors', 'ADI', 'Analog Devices, Inc.'),
    ('Technology', 'Semiconductors', 'MRVL', 'Marvell Technology, Inc.'),
    ('Technology', 'Semiconductors', 'INTC', 'Intel Corporation'),
    ('Technology', 'Semiconductors', 'NXPI', 'NXP Semiconductors N.V.'),
    ('Technology', 'Semiconductors', 'MCHP', 'Microchip Technology Incorporated'),
    ('Technology', 'Semiconductors', 'MPWR', 'Monolithic Power Systems, Inc.'),
    ('Technology', 'Semiconductors', 'ON', 'ON Semiconductor Corporation'),
    ('Technology', 'Semiconductors', 'STM', 'STMicroelectronics N.V.'),
    ('Technology', 'Semiconductors', 'ASX', 'ASE Technology Holding Co., Ltd.'),
    ('Technology', 'Semiconductors', 'UMC', 'United Microelectronics Corporation'),
    ('Technology', 'Semiconductors', 'SWKS', 'Skyworks Solutions, Inc.'),
    ('Technology', 'Semiconductors', 'MTSI', 'MACOM Technology Solutions Holdings, Inc.'),
    ('Technology', 'Semiconductors', 'LSCC', 'Lattice Semiconductor Corporation'),
]
